### PR TITLE
onMeasureLayout feature - tested OK in iOS and Android

### PR DESCRIPTION
**Pull request by eactisgrosso**
Hello @shahnawaz, thanks for the barcode mask !!! 

I'm using it for text recognition, and it comes in handy to be able to detect when the text is within the mask's coordinates:

Screenshot_1565398838

I added the functionality and tested it successfully on Android and iOS.
Cheers!

Ezequiel

### CODE REVIEW

**Comment by shahnawaz** [comment]
@eactisgrosso This is awesome!

Let me check this feature and get back to you.

**Comment by eactisgrosso** [comment]
@shahnawaz great !!! 

Also, in my local version I added an edgeRadius prop, like this:
` <BarcodeMask
            width={W_WIDTH * 0.9 * 1.55}
            height={W_WIDTH * 0.9}
            edgeColor={theme.brandPrimary4}
            edgeBorderWidth={8}
            edgeWidth={30}
            edgeHeight={30}
            edgeRadius={10}
            onMeasureLayout={measurement => {
              setScanLayout(measurement);
            }}
          />`

IMG_0737

Let me know if this one also makes sense to you, so I can add it as a new feature in another PR.
Cheers!

**Comment by shahnawaz** [comment]
Hi @eactisgrosso 

Highly appreciate your work here 👍 

Your suggestion for `onMeasureLayout` has been added in v1.2.0

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-native-barcode-mask/v/1.2.0)
- [GitHub release](https://github.com/shahnawaz/react-native-barcode-mask/releases/tag/v1.2.0)

Your `edgeRadius` idea seems cool as well.
If you are still tracking this thread, you can surely create a separate pull request for `edgeRadius` and we will merge that.

**Comment by eactisgrosso** [comment]
Great @shahnawaz! 

As for the edgeRadius, I'm on it.

**Pull request closed without merging**
